#!/bin/bash

set -e
set -u
set -x

JOB_NAME=redis

LOG_DIR=/var/vcap/sys/log/$JOB_NAME
PID_DIR=/var/vcap/sys/run/$JOB_NAME

PID_FILE=$PID_DIR/$JOB_NAME.pid

case $1 in
  start)
    mkdir -p $PID_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PID_FILE

    exec /var/vcap/packages/redis/bin/redis-server \
         >>$LOG_DIR/$JOB_NAME.stdout.log \
         2>>$LOG_DIR/$JOB_NAME.stderr.log
    ;;

  stop)
    ;;
  *)
    echo "Usage: redis_ctl {start|stop}"
    ;;

esac
exit 0
